# ---------------- #
#   Main Configs   #
# ---------------- #
baseurl:
url: https://www.0x16.top
date_format: "ordinal"
title: "0x16 个人笔记"
subtitle: "记录点点滴滴"
description:
keywords: 笔记
timezone: Asia/Shanghai
encoding: "utf-8"
side_bar_repo_limit: 5

# ---------------- #
#      Author      #
# ---------------- #
author: '0x16.top'
organization: '0x16.top'
organization_url: https://www.0x16.top
github_username: wonphe
location: Suzhou, China
email: wonphe@163.com

# ---------------- #
#    Navigation    #
# ---------------- #
navs:
  -
    href: /
    label: 首页

  -
    href: /categories/
    label: 分类

#   -
#     href: /archives/
#     label: 归档

  -
    href: /wiki/
    label: 维基

#   -
#     href: /links/
#     label: 链接

  -
    href: /about/
    label: 关于

# ---------------- #
#       RSS        #
# ---------------- #
subscribe_rss: /feed.xml

# ---------------- #
#      Jekyll      #
# ---------------- #
markdown: kramdown
kramdown:
    input: GFM
highlighter: rouge
paginate: 8
lsi: false
quiet: false
excerpt_separator: "\n\n"
permalink: /:year/:month/:day/:title/
gems:
    - jekyll-github-metadata
    - rouge
#     - jekyll-html-pipeline
    - jekyll-paginate
    - jekyll-sitemap
    - jekyll-feed
    - jemoji
#     - jekyll-mentions
collections:
    wiki:
        output: true
        permalink: /wiki/:path/

repository: wonphe/wonphe.github.io

# ---------------- #
#      Comments    #
# ---------------- #
# support provider: disqus, gitment, gitalk
comments_provider: gitalk
# !!!重要!!! 请修改下面这些信息为你自己申请的
# !!!Important!!! Please modify infos below to yours
# https://disqus.com
disqus:
    username: 
# https://imsun.net/posts/gitment-introduction/
gitment:
    owner: wonphe
    repo: wonphe.github.io
    oauth:
        client_id: 765f16fee8ed51bcd04e
        client_secret: ac024984eaf4b1f0a99b038dde4f54d8885844e5
# https://github.com/gitalk/gitalk#install
gitalk:
    owner: wonphe
    repo: wonphe.github.io
    clientID: 765f16fee8ed51bcd04e
    clientSecret: ac024984eaf4b1f0a99b038dde4f54d8885844e5
# 在使用其它评论组件时可点击显示 Disqus
lazy_load_disqus : false

# ---------------- #
#      Search      #
# ---------------- #
simple_jekyll_search:
    # 是否支持全文搜索
    fulltext: false
    # 最多显示多少条搜索结果
    limit: 10

# ---------------- #
#    Analytics     #
# ---------------- #
google:
    analytics_id: UA-80669434-1
